### ISSUE TITLE
innerText is not supported in Firefox

### ISSUE THREAD

**Issue by danhawkes** [hannesstruss/godot#15]
Graphs in the demo page fail to render because the JSON is being retrieved from the node with `innerText`:

```
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data report.html:197:15
TypeError: DATA is undefined
```

Related: http://stackoverflow.com/questions/1359469/innertext-works-in-ie-but-not-in-firefox

**Comment by hannesstruss** [comment]
thanks for reporting this! I'll have a look.
